"""End-to-end AutoPatch-RL loop.

usage:
    python -m core.orchestrator
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

import yaml
from dotenv import load_dotenv
from rich.console import Console
from rich.table import Table

from agents import policy_writer, red_agent, reporter
from core import judge, policy_compiler, probe_runner, red_probe_runner, runner, state_store

ROOT = Path(__file__).resolve().parent.parent
BASELINE_POLICY = ROOT / "policies" / "baseline" / "policy_intent.yaml"
LATEST_LINK = ROOT / "policies" / "generated" / "latest"

console = Console()


def _print_probe_table(it: int, results: list[dict], title_suffix: str = "") -> None:
    table = Table(title=f"iter-{it:03d} probes{title_suffix}")
    table.add_column("probe")
    table.add_column("cat")
    table.add_column("sev")
    table.add_column("expected")
    table.add_column("actual")
    table.add_column("evidence")
    for r in results:
        actual = r["actual"]
        cat = r["category"]
        ok = (
            (cat in ("attack_surface", "red_team", "red_dynamic") and actual == "blocked")
            or (cat == "regression" and actual == "pass")
        )
        style = "green" if ok else "red"
        cat_short = {"attack_surface": "att", "red_team": "red", "red_dynamic": "dyn", "regression": "reg"}.get(cat, cat[:3])
        table.add_row(
            r["probe_id"],
            cat_short,
            r["severity"][:1],
            r["expected"],
            f"[{style}]{actual}[/{style}]",
            (r.get("evidence") or "")[:60],
        )
    console.print(table)


def _link_latest(iter_dir: Path) -> None:
    LATEST_LINK.parent.mkdir(parents=True, exist_ok=True)
    if LATEST_LINK.exists() or LATEST_LINK.is_symlink():
        LATEST_LINK.unlink()
    try:
        LATEST_LINK.symlink_to(iter_dir.resolve(), target_is_directory=True)
    except OSError:
        shutil.copytree(iter_dir, LATEST_LINK, dirs_exist_ok=True)


def main() -> int:
    load_dotenv(ROOT / ".env")
    max_iters = int(os.environ.get("MAX_ITERS", "6"))

    console.rule("[bold]AutoPatch-RL")
    console.print(
        f"baseline: [cyan]{BASELINE_POLICY}[/cyan]\n"
        f"max_iters: {max_iters}\n"
        f"llm: {os.environ.get('OPENAI_BASE_URL', '(none)')}"
        f"  model={os.environ.get('OPENAI_MODEL', '(none)')}"
    )

    run_dir = state_store.new_run_dir()
    console.print(f"run_dir: [yellow]{run_dir}[/yellow]")

    current_yaml = BASELINE_POLICY.read_text()
    prev_yaml: str | None = None
    history: list[dict] = []
    last_it_dir: Path | None = None

    for it in range(max_iters):
        console.rule(f"[bold green]iter {it}")
        it_dir = state_store.iter_dir(run_dir, it)
        intent_path = it_dir / "policy_intent.yaml"
        intent_path.write_text(current_yaml)

        try:
            policy_compiler.compile_intent(intent_path, it_dir)
        except Exception as e:
            console.print(f"[red]compile failed:[/red] {e}")
            current_yaml = BASELINE_POLICY.read_text()
            continue

        _link_latest(it_dir)

        try:
            runner.up(it_dir / "docker_run.sh")
        except Exception as e:
            console.print(f"[red]docker up failed:[/red] {e}")
            console.print("policy that failed to start:")
            console.print(current_yaml)
            current_yaml = BASELINE_POLICY.read_text() if prev_yaml is None else prev_yaml
            continue

        if not runner.wait_ready(timeout=20.0):
            console.print("[yellow]container did not become healthy in 20s[/yellow]")
            console.print(runner.container_logs(80))

        fixed_results = probe_runner.run_all(it)
        _print_probe_table(it, fixed_results, " (fixed)")

        # --- Red agent: dynamic LLM-generated bypass payloads ---
        dyn_results: list[dict] = []
        waf_json_path = it_dir / "waf_rules.json"
        waf_config = {}
        if waf_json_path.exists():
            import json as _json
            waf_config = _json.loads(waf_json_path.read_text())

        payloads, red_rationale, red_source = red_agent.generate_payloads(
            waf_config, fixed_results, it, history,
        )
        if payloads:
            console.print(
                f"[dim]red_agent source={red_source}, "
                f"{len(payloads)} dynamic payloads[/dim]"
            )
            dyn_results = red_probe_runner.run_all(payloads, it)
            _print_probe_table(it, dyn_results, " (dynamic red)")
            if red_rationale:
                console.print(f"[dim italic]red_rationale: {red_rationale[:200]}[/dim italic]")
        else:
            console.print(f"[dim]red_agent: no dynamic payloads (source={red_source})[/dim]")

        # --- Merge all results ---
        results = fixed_results + dyn_results
        score_dict = judge.score(results)
        console.print(judge.summary_line(results, score_dict))

        state_store.save_iteration(it_dir, current_yaml, results, score_dict, prev_yaml)

        # Save dynamic payloads and results for inspection
        if payloads:
            import json as _json
            (it_dir / "red_payloads.json").write_text(
                _json.dumps(payloads, indent=2, ensure_ascii=False)
            )
            (it_dir / "red_dynamic_results.json").write_text(
                _json.dumps(dyn_results, indent=2, ensure_ascii=False)
            )

        history.append(
            {
                "iter": it,
                "score": score_dict["total"],
                "failing": [
                    r["probe_id"]
                    for r in results
                    if (r["category"] in judge.ATTACK_CATEGORIES and r["actual"] == "allowed")
                    or (r["category"] == "regression" and r["actual"] == "fail")
                ],
                "dyn_bypasses": [
                    r["probe_id"]
                    for r in dyn_results
                    if r["actual"] == "allowed"
                ],
            }
        )
        last_it_dir = it_dir

        if judge.is_terminal(results):
            console.print(f"[bold green]✓ terminal state reached at iter {it}")
            break

        if it == max_iters - 1:
            console.print(f"[yellow]hit MAX_ITERS={max_iters} without terminal state")
            break

        prev_yaml = current_yaml
        new_yaml, source = policy_writer.propose_next(current_yaml, results, history)
        console.print(f"[dim]policy_writer source={source}[/dim]")
        current_yaml = new_yaml

    if last_it_dir is not None:
        state_store.finalize(run_dir, last_it_dir)

    runner.down()
    report = reporter.write_report(run_dir)
    console.rule("[bold]done")
    console.print(f"report: [bold]{report}[/bold]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
